# This is a basic workflow to help you get started with Actions

name: Build Carthage FirebaseGoogleAuthUI.framework

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths-ignore:
      - './.github/workflows/release_firebase_authui.yml'

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    env:
      working-directory: ./Auth

    steps:
      - uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: 11.7

      - name: Carthage bootstrap
        run: carthage bootstrap
        working-directory: ${{env.working-directory}}

      - name: Carthage build
        run: carthage build --no-skip-current --log-path ./carthage.log
        working-directory: ${{env.working-directory}}

      - name: Upload Carthage log to artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with: 
          name: carthage.log
          path: ${{env.working-directory}}/carthage.log
