# This is a basic workflow to help you get started with Actions

name: Build Carthage FirebaseAuthUI.framework

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths-ignore:
      - ./.github/workflows/release_firebaseauthui.yml

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    env:
      working-directory: ./Auth

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: 11.7

      # Run Carthage bootstrap
      - name: Carthage bootstrap
        run: carthage bootstrap
        working-directory: ${{env.working-directory}}

      # Run Carthage build
      - name: Carthage build
        run: carthage build --no-skip-current --log-path ./carthage.log
        working-directory: ${{env.working-directory}}

      # Upload Carthage log
      - name: Upload FirebaseAuthUI framework to artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with: 
          name: carthage.log
          path: ${{env.working-directory}}/carthage.log
