# This is a basic workflow to help you get started with Actions

name: Create FirebaseUI/Auth Carthage framework

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    env:
      working-directory: ./Auth

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: 12.2

      # Run Carthage bootstrap
      - name: Carthage bootstrap
        run: carthage bootstrap
        working-directory: ${{env.working-directory}}

      # Run Carthage build
      - name: Carthage build
        run: ./carthage.xcode12.sh build --no-skip-current
        working-directory: ${{env.working-directory}}      